#!/bin/bash

# Set to a destination folder to copy files to
DEST="${HOME}/transfers/priv"

make clean
make
[ $? -eq 0 ] && {
  [ -x ../trim_lslo ] && {
    echo "Trimming comments from optimized LSL scripts"
    ../trim_lslo
  }
}

[ "$1" == "-c" ] && {
  mkdir -p ${DEST}
  cp Red_Tea.lslo ${DEST}/Red_Tea
  cp Region_Stats.lslo ${DEST}/Region_Stats
  cp Saucer.lslo ${DEST}/Saucer
  cp Teacup.lslo ${DEST}/Teacup
  cp Tea_Strainer.lslo ${DEST}/Tea_Strainer
}
